name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/wedding-guest-api
            git pull origin main
            npm install --production
            npm run init-db
            pm2 restart wedding-api
